"""
Voice Studio — FastAPI entrypoint.

Routes:
  GET  /api/health              — liveness + server-config status
  GET  /api/engines             — list TTS engines with availability
  GET  /api/presets             — list the design preset speakers
  POST /api/clone               — clone a voice from an uploaded audio clip
                                  (save=true → JSON profile; save=false → MP3 bytes)
  POST /api/design              — persist a designed voice → JSON profile
  POST /api/design/preview      — synth a designed voice without saving → MP3 bytes
  GET  /api/profiles            — list local profiles
  GET  /api/profiles/{id}       — fetch one profile
  GET  /api/profiles/{id}/sample — stream the preview MP3
  DELETE /api/profiles/{id}     — delete local + remote
  POST /api/profiles/{id}/sync  — re-push to Reader if missing there

All routes bind to 127.0.0.1 only via start.sh. CORS open to localhost
for the Next.js frontend.
"""

from __future__ import annotations

import logging
import os
import shutil
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv
from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse, Response
from pydantic import BaseModel, Field

import profiles
import reader_client
import tts

# Load .env.local from the repo root (one level up from backend/).
ROOT = Path(__file__).parent.parent
load_dotenv(ROOT / ".env.local")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(name)s: %(message)s",
)
log = logging.getLogger("voice-studio")

app = FastAPI(title="Voice Studio", version="0.1.0")

# Next.js dev server talks to us from localhost:3007.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3007", "http://127.0.0.1:3007"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


# -------- Models --------

class HealthResponse(BaseModel):
    ok: bool
    reader_configured: bool
    reader_base_url: Optional[str]
    reader_token_set: bool
    device: str
    default_engine: str
    engines: list[dict]


class ConfigUpdate(BaseModel):
    reader_base_url: Optional[str] = None
    reader_auth_token: Optional[str] = None


class DesignRequest(BaseModel):
    name: str = Field(min_length=1, max_length=60)
    base_voice: str
    engine: str = Field("xtts")  # "f5" or "xtts"
    language: str = Field("en", min_length=2, max_length=5)
    pitch: float = Field(0.0, ge=-6.0, le=6.0)      # semitones
    speed: float = Field(1.0, ge=0.5, le=2.0)
    temperature: float = Field(0.7, ge=0.1, le=1.5)
    # XTTS only: built-in speaker name. When set, overrides reference-clip
    # cloning — gives us explicit access to female / male / accented voices.
    speaker_name: Optional[str] = None
    # Optional 4-color palette computed by the frontend from the sliders.
    # Shipped to Reader with the profile so the sphere there matches the
    # one the user saw here when saving.
    colors: Optional[list[str]] = None
    preview_text: str = Field(
        "Hello. This is a preview of my voice, generated by Voice Studio.",
        max_length=400,
    )


class ProfileResponse(BaseModel):
    id: str
    name: str
    kind: str
    engine: str
    created_at: str
    design: dict
    synced: bool


def _to_response(p: profiles.VoiceProfile) -> ProfileResponse:
    return ProfileResponse(
        id=p.id, name=p.name, kind=p.kind, engine=p.engine,
        created_at=p.created_at, design=p.design, synced=p.synced,
    )


# -------- Routes --------

@app.get("/api/health", response_model=HealthResponse)
def health():
    return HealthResponse(
        ok=True,
        reader_configured=reader_client.is_configured(),
        reader_base_url=reader_client.current_base_url(),
        reader_token_set=reader_client.token_is_set(),
        device=os.environ.get("TTS_DEVICE", "mps"),
        default_engine=tts.DEFAULT_ENGINE,
        engines=tts.list_engines(),
    )


@app.post("/api/config")
def update_config(cfg: ConfigUpdate):
    """Update the in-memory Reader connection. Lives only in the running
    backend process — restart reverts to .env.local values. This keeps
    secrets out of any persisted file."""
    reader_client.set_config(cfg.reader_base_url, cfg.reader_auth_token)
    return {
        "reader_configured": reader_client.is_configured(),
        "reader_base_url": reader_client.current_base_url(),
        "reader_token_set": reader_client.token_is_set(),
    }


@app.get("/api/engines")
def list_engines():
    """Returns the catalog of available engines with load state.
    Frontend uses this for the engine picker."""
    return {"default": tts.DEFAULT_ENGINE, "engines": tts.list_engines()}


@app.get("/api/xtts/speakers")
def list_xtts_speakers():
    """List XTTS's built-in speakers (gendered) so the Design tab can
    offer a 'pick a base voice' dropdown with actual female/male options,
    not just one coral-ish cloned reference clip."""
    try:
        xtts = tts.get_engine("xtts")
    except ValueError:
        raise HTTPException(404, "XTTS engine not registered")
    if not xtts.is_available():
        raise HTTPException(501, "XTTS not installed (pip install TTS>=0.22)")
    try:
        speakers = xtts.list_speakers()  # type: ignore[attr-defined]
    except Exception as e:
        log.exception("xtts speakers")
        raise HTTPException(500, f"Couldn't load XTTS speakers: {e}")
    return {"speakers": speakers}


@app.get("/api/presets")
def list_presets():
    return {"presets": tts.PRESETS}


@app.post("/api/clone")
async def clone_voice(
    name: str = Form("Preview", min_length=1, max_length=60),
    audio_file: UploadFile = File(...),
    engine_id: str = Form("xtts"),
    language: str = Form("en"),
    preview_text: str = Form(
        "Hello. This is a preview of my cloned voice, generated by Voice Studio."
    ),
    ref_text: Optional[str] = Form(None),
    upload: bool = Form(True),
    save: bool = Form(True),
):
    """Clone a voice from an uploaded audio clip.

    If save=True (default), creates a local profile and (if upload=True)
    pushes metadata + sample to Reader. Returns the ProfileResponse JSON.

    If save=False, synthesizes but does NOT persist anything — returns
    the raw audio/mpeg bytes. Used by the "Preview" button on the frontend
    so the user can listen before committing.
    """
    try:
        engine = tts.get_engine(engine_id)
    except ValueError as e:
        raise HTTPException(400, str(e))

    # Read the uploaded clip once into memory. Both the save and preview
    # paths need it — the save path persists it as source.wav, the preview
    # path writes it to a tempfile for the synthesis engine.
    raw = await audio_file.read()
    if not raw:
        raise HTTPException(400, "audio_file is empty")
    src_ext = os.path.splitext(audio_file.filename or "")[1].lower() or ".wav"

    if not save:
        # Preview-only path. Write to a tempfile, synthesize, stream bytes back.
        import tempfile
        with tempfile.NamedTemporaryFile(suffix=src_ext, delete=False) as tf:
            tf.write(raw)
            tmp_path = tf.name
        try:
            result = engine.synthesize(
                text=preview_text,
                ref_audio_path=tmp_path,
                ref_text=ref_text,
                speed=1.0,
                language=language,
            )
            mp3 = tts.encode_mp3(result)
        except Exception as e:
            log.exception("Preview clone synthesis failed")
            raise HTTPException(500, f"Synthesis failed: {e}")
        finally:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass
        return Response(content=mp3, media_type="audio/mpeg")

    # Save path (default).
    profile = profiles.VoiceProfile(
        id=profiles.new_id(),
        name=name.strip(),
        kind="cloned",
        engine=engine.id,
        created_at=profiles._now(),
        design={"language": language},
    )
    profile.dir().mkdir(parents=True, exist_ok=True)
    src_path = profile.dir() / f"source{src_ext}"
    src_path.write_bytes(raw)

    try:
        result = engine.synthesize(
            text=preview_text,
            ref_audio_path=str(src_path),
            ref_text=ref_text,
            speed=1.0,
            language=language,
        )
        mp3 = tts.encode_mp3(result)
        profile.sample_path().write_bytes(mp3)
    except Exception as e:
        log.exception("Clone synthesis failed")
        shutil.rmtree(profile.dir(), ignore_errors=True)
        raise HTTPException(500, f"Synthesis failed: {e}")

    profiles.save(profile)

    if upload and reader_client.is_configured():
        try:
            reader_client.upload_profile(profile)
            profile.synced = True
            profiles.save(profile)
        except Exception as e:
            log.warning("Upload to Reader failed: %s", e)
            # Local profile still saved — user can retry via /sync.

    return _to_response(profile)


def _synthesize_design(req: "DesignRequest") -> bytes:
    """Core synthesis used by both save and preview paths. Raises HTTPException
    on failure so the route handlers can pass-through the error.

    We log each phase separately so when a request dies we know which step
    actually blew up (ref resolution / engine load / synthesis / pitch / mp3).
    """
    log.info(
        "design: engine=%s lang=%s base=%s pitch=%.2f speed=%.2f temp=%.2f",
        req.engine, req.language, req.base_voice, req.pitch, req.speed, req.temperature,
    )

    try:
        ref_path, ref_text = tts.resolve_preset(req.base_voice)
        log.info("design: resolved preset → %s", ref_path)
    except (ValueError, FileNotFoundError) as e:
        log.warning("design: preset resolution failed: %s", e)
        raise HTTPException(400, str(e))

    try:
        engine = tts.get_engine(req.engine)
    except ValueError as e:
        raise HTTPException(400, str(e))

    try:
        if req.speaker_name:
            log.info(
                "design: synthesizing with %s on %s, speaker=%s…",
                engine.id, engine.device, req.speaker_name,
            )
        else:
            log.info(
                "design: synthesizing with %s on %s (from ref clip)…",
                engine.id, engine.device,
            )
        result = engine.synthesize(
            text=req.preview_text,
            ref_audio_path=ref_path,
            ref_text=ref_text,
            speed=req.speed,
            language=req.language,
            speaker_name=req.speaker_name,
        )
        log.info(
            "design: synth ok — %d samples @ %d Hz",
            len(result.audio), result.sample_rate,
        )
        if abs(req.pitch) > 0.01:
            result = tts.pitch_shift(result, req.pitch)
            log.info("design: pitch shifted by %.2f semitones", req.pitch)
        mp3 = tts.encode_mp3(result)
        log.info("design: encoded %d bytes of mp3", len(mp3))
        return mp3
    except HTTPException:
        raise
    except Exception as e:
        log.exception("design: synthesis failed")
        raise HTTPException(500, f"Synthesis failed: {e}")


@app.post("/api/design/preview")
def preview_design(req: DesignRequest):
    """Synthesize without persisting. Returns audio/mpeg bytes for in-browser
    playback. The user can tweak sliders and call this repeatedly before
    committing via POST /api/design."""
    mp3 = _synthesize_design(req)
    return Response(content=mp3, media_type="audio/mpeg")


@app.post("/api/design", response_model=ProfileResponse)
def design_voice(req: DesignRequest, upload: bool = True):
    """Persist a 'designed' voice: synthesize, save locally, optionally
    push to Reader."""
    try:
        engine = tts.get_engine(req.engine)
    except ValueError as e:
        raise HTTPException(400, str(e))

    mp3 = _synthesize_design(req)

    profile = profiles.VoiceProfile(
        id=profiles.new_id(),
        name=req.name.strip(),
        kind="designed",
        engine=engine.id,
        created_at=profiles._now(),
        design={
            "base_voice": req.base_voice,
            "pitch": req.pitch,
            "speed": req.speed,
            "temperature": req.temperature,
            "language": req.language,
            "speaker_name": req.speaker_name,
            # Store the exact palette the user saw so Reader can reproduce it.
            "colors": req.colors,
        },
    )
    profile.dir().mkdir(parents=True, exist_ok=True)
    profile.sample_path().write_bytes(mp3)
    profiles.save(profile)

    if upload and reader_client.is_configured():
        try:
            reader_client.upload_profile(profile)
            profile.synced = True
            profiles.save(profile)
        except Exception as e:
            log.warning("Upload to Reader failed: %s", e)

    return _to_response(profile)


@app.get("/api/profiles")
def list_profiles():
    return {"profiles": [_to_response(p).model_dump() for p in profiles.list_all()]}


@app.get("/api/profiles/{profile_id}", response_model=ProfileResponse)
def get_profile(profile_id: str):
    p = profiles.load(profile_id)
    if p is None:
        raise HTTPException(404, "Profile not found")
    return _to_response(p)


@app.get("/api/profiles/{profile_id}/sample")
def get_sample(profile_id: str):
    p = profiles.load(profile_id)
    if p is None or not p.sample_path().exists():
        raise HTTPException(404, "Sample not found")
    return FileResponse(p.sample_path(), media_type="audio/mpeg")


@app.delete("/api/profiles/{profile_id}")
def delete_profile(profile_id: str):
    p = profiles.load(profile_id)
    if p is None:
        raise HTTPException(404, "Profile not found")
    # Best-effort remote delete first; don't block local delete on failure.
    if reader_client.is_configured():
        try:
            reader_client.delete_profile(profile_id)
        except Exception as e:
            log.warning("Remote delete failed (will delete locally anyway): %s", e)
    profiles.delete(profile_id)
    return {"deleted": profile_id}


@app.post("/api/profiles/{profile_id}/sync", response_model=ProfileResponse)
def sync_profile(profile_id: str):
    p = profiles.load(profile_id)
    if p is None:
        raise HTTPException(404, "Profile not found")
    if not reader_client.is_configured():
        raise HTTPException(400, "Reader not configured (set READER_BASE_URL + READER_AUTH_TOKEN)")
    try:
        reader_client.upload_profile(p)
    except Exception as e:
        raise HTTPException(502, f"Upload failed: {e}")
    p.synced = True
    profiles.save(p)
    return _to_response(p)
