"use client";

import { useCallback, useEffect, useState } from "react";
import { designVoice, listPresets, type Preset, type Profile } from "@/lib/api";
import { VoiceSphere } from "@/components/VoiceSphere";

type Props = {
  onCreated: (p: Profile) => void;
};

type Sliders = {
  pitch: number;      // -6..6 semitones
  speed: number;      // 0.5..2.0
  temperature: number; // 0.1..1.5
};

const DEFAULT_SLIDERS: Sliders = { pitch: 0, speed: 1, temperature: 0.7 };

export function DesignTab({ onCreated }: Props) {
  const [presets, setPresets] = useState<Preset[]>([]);
  const [baseVoice, setBaseVoice] = useState("");
  const [name, setName] = useState("");
  const [previewText, setPreviewText] = useState(
    "Hello. This is a preview of my designed voice, generated by Voice Studio."
  );
  const [sliders, setSliders] = useState<Sliders>(DEFAULT_SLIDERS);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<Profile | null>(null);

  useEffect(() => {
    listPresets()
      .then((ps) => {
        setPresets(ps);
        if (ps.length && !baseVoice) setBaseVoice(ps[0].id);
      })
      .catch((e) => setError((e as Error).message));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const update = <K extends keyof Sliders>(key: K, val: Sliders[K]) =>
    setSliders((s) => ({ ...s, [key]: val }));

  const onSubmit = useCallback(async () => {
    if (!name.trim() || !baseVoice || busy) return;
    setBusy(true);
    setError(null);
    setResult(null);
    try {
      const p = await designVoice({
        name: name.trim(),
        baseVoice,
        pitch: sliders.pitch,
        speed: sliders.speed,
        temperature: sliders.temperature,
        previewText: previewText.trim() || undefined,
      });
      setResult(p);
      onCreated(p);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(false);
    }
  }, [name, baseVoice, sliders, previewText, busy, onCreated]);

  // Seed for preview sphere — changes as knobs move so user gets visual
  // feedback before hitting synthesize.
  const previewSeed = `${baseVoice}:${sliders.pitch.toFixed(1)}:${sliders.speed.toFixed(2)}:${sliders.temperature.toFixed(2)}`;

  return (
    <div className="grid md:grid-cols-[1fr_320px] gap-8 items-start">
      <div className="space-y-5">
        <div>
          <label className="block text-sm font-medium mb-1.5">Voice name</label>
          <input
            className="input"
            placeholder="e.g. Narrator Soft, Calm Reader, Warm Alto"
            value={name}
            onChange={(e) => setName(e.target.value)}
            maxLength={60}
          />
        </div>

        <div>
          <label className="block text-sm font-medium mb-1.5">Base voice</label>
          <select
            className="select"
            value={baseVoice}
            onChange={(e) => setBaseVoice(e.target.value)}
            disabled={!presets.length}
          >
            {presets.length === 0 && <option>Loading presets…</option>}
            {presets.map((p) => (
              <option key={p.id} value={p.id}>
                {p.label}
              </option>
            ))}
          </select>
        </div>

        <Slider
          label="Pitch"
          unit="semitones"
          min={-6}
          max={6}
          step={0.5}
          value={sliders.pitch}
          onChange={(v) => update("pitch", v)}
        />
        <Slider
          label="Speed"
          unit="x"
          min={0.5}
          max={2}
          step={0.05}
          value={sliders.speed}
          onChange={(v) => update("speed", v)}
        />
        <Slider
          label="Temperature"
          unit=""
          min={0.1}
          max={1.5}
          step={0.05}
          value={sliders.temperature}
          onChange={(v) => update("temperature", v)}
          hint="Higher = more expressive, more variance"
        />

        <div>
          <label className="block text-sm font-medium mb-1.5">Preview text</label>
          <textarea
            className="input"
            rows={2}
            value={previewText}
            onChange={(e) => setPreviewText(e.target.value)}
          />
        </div>

        <div className="flex items-center gap-3 pt-2">
          <button
            className="btn btn-primary"
            onClick={onSubmit}
            disabled={busy || !name.trim() || !baseVoice}
          >
            {busy ? "Synthesizing…" : "Create voice"}
          </button>
          <button
            className="btn btn-ghost"
            onClick={() => setSliders(DEFAULT_SLIDERS)}
            disabled={busy}
          >
            Reset sliders
          </button>
          {error && <span className="text-sm text-red-500">{error}</span>}
        </div>
      </div>

      <div className="flex flex-col items-center">
        <VoiceSphere seed={result?.id ?? previewSeed} size={220} />
        {result ? (
          <div className="mt-5 w-full space-y-3">
            <div className="text-center">
              <div className="font-medium">{result.name}</div>
              <div className="text-xs text-[color:var(--muted)] mt-0.5">
                Designed · {result.synced ? "synced to Reader" : "local only"}
              </div>
            </div>
            <audio
              controls
              className="w-full"
              src={`/api/profiles/${result.id}/sample`}
            />
          </div>
        ) : (
          <div className="mt-5 text-center text-xs text-[color:var(--muted)] max-w-xs">
            Palette updates live as you move the sliders. Hit <em>Create voice</em>{" "}
            to synthesize a preview.
          </div>
        )}
      </div>
    </div>
  );
}

function Slider(props: {
  label: string;
  unit: string;
  min: number;
  max: number;
  step: number;
  value: number;
  onChange: (v: number) => void;
  hint?: string;
}) {
  return (
    <div>
      <div className="flex items-baseline justify-between mb-1.5">
        <label className="block text-sm font-medium">{props.label}</label>
        <span className="text-xs text-[color:var(--muted)] tabular-nums">
          {props.value.toFixed(props.step < 0.1 ? 2 : 1)}
          {props.unit ? ` ${props.unit}` : ""}
        </span>
      </div>
      <input
        type="range"
        min={props.min}
        max={props.max}
        step={props.step}
        value={props.value}
        onChange={(e) => props.onChange(Number(e.target.value))}
        className="w-full accent-[color:var(--accent)]"
      />
      {props.hint && (
        <div className="text-xs text-[color:var(--muted)] mt-1">{props.hint}</div>
      )}
    </div>
  );
}
