"use client";

import { useCallback, useEffect, useState } from "react";
import {
  designVoice,
  listEngines,
  listPresets,
  previewDesign,
  sampleUrl,
  type Engine,
  type Preset,
  type Profile,
} from "@/lib/api";
import { EnginePicker, useEngineChoice } from "@/components/EnginePicker";
import { VoiceSphere } from "@/components/VoiceSphere";

type Props = {
  onCreated: (p: Profile) => void;
};

type Sliders = {
  pitch: number;      // -6..6 semitones
  speed: number;      // 0.5..2.0
  temperature: number; // 0.1..1.5
};

const DEFAULT_SLIDERS: Sliders = { pitch: 0, speed: 1, temperature: 0.7 };

export function DesignTab({ onCreated }: Props) {
  const [presets, setPresets] = useState<Preset[]>([]);
  const [baseVoice, setBaseVoice] = useState("");
  const [name, setName] = useState("");
  const [previewText, setPreviewText] = useState(
    "Hello. This is a preview of my designed voice, generated by Voice Studio."
  );
  const [sliders, setSliders] = useState<Sliders>(DEFAULT_SLIDERS);
  const [busy, setBusy] = useState<"preview" | "save" | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<Profile | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [audioPlaying, setAudioPlaying] = useState(false);

  useEffect(() => {
    return () => {
      if (previewUrl) URL.revokeObjectURL(previewUrl);
    };
  }, [previewUrl]);

  const [engines, setEngines] = useState<Engine[] | null>(null);
  const [backendDefault, setBackendDefault] = useState<string | null>(null);
  const [engine, setEngine] = useEngineChoice(engines, backendDefault);
  const [language, setLanguage] = useState("en");

  useEffect(() => {
    listPresets()
      .then((ps) => {
        setPresets(ps);
        if (ps.length && !baseVoice) setBaseVoice(ps[0].id);
      })
      .catch((e) => setError((e as Error).message));
    listEngines()
      .then((d) => {
        setEngines(d.engines);
        setBackendDefault(d.default);
      })
      .catch(() => {});
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Keep language valid for the chosen engine.
  useEffect(() => {
    if (!engines || !engine) return;
    const e = engines.find((x) => x.id === engine);
    if (e && !e.languages.includes(language)) {
      setLanguage(e.languages[0] ?? "en");
    }
  }, [engine, engines, language]);

  const update = <K extends keyof Sliders>(key: K, val: Sliders[K]) =>
    setSliders((s) => ({ ...s, [key]: val }));

  const selectPreset = (id: string) => {
    setBaseVoice(id);
    const p = presets.find((x) => x.id === id);
    if (p) {
      setSliders({
        pitch: p.default_pitch,
        speed: p.default_speed,
        temperature: p.default_temperature,
      });
    }
  };

  const onPreview = useCallback(async () => {
    if (!baseVoice || !engine || busy) return;
    setBusy("preview");
    setError(null);
    if (previewUrl) {
      URL.revokeObjectURL(previewUrl);
      setPreviewUrl(null);
    }
    try {
      const url = await previewDesign({
        baseVoice,
        engine,
        language,
        pitch: sliders.pitch,
        speed: sliders.speed,
        temperature: sliders.temperature,
        previewText: previewText.trim() || undefined,
      });
      setPreviewUrl(url);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  }, [baseVoice, engine, language, sliders, previewText, busy, previewUrl]);

  const onSave = useCallback(async () => {
    if (!name.trim() || !baseVoice || !engine || busy) return;
    setBusy("save");
    setError(null);
    setResult(null);
    try {
      const p = await designVoice({
        name: name.trim(),
        baseVoice,
        engine,
        language,
        pitch: sliders.pitch,
        speed: sliders.speed,
        temperature: sliders.temperature,
        previewText: previewText.trim() || undefined,
      });
      setResult(p);
      onCreated(p);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  }, [name, baseVoice, engine, language, sliders, previewText, busy, onCreated]);

  // Seed for preview sphere — changes as knobs move so user gets visual
  // feedback before hitting synthesize.
  const previewSeed = `${engine}:${baseVoice}:${sliders.pitch.toFixed(1)}:${sliders.speed.toFixed(2)}:${sliders.temperature.toFixed(2)}`;

  return (
    <div className="grid md:grid-cols-[1fr_320px] gap-8 items-start">
      <div className="space-y-5">
        <div>
          <label className="block text-sm font-medium mb-1.5">Voice name</label>
          <input
            className="input"
            placeholder="e.g. Narrator Soft, Calm Reader, Warm Alto"
            value={name}
            onChange={(e) => setName(e.target.value)}
            maxLength={60}
          />
        </div>

        {engines && engine && (
          <EnginePicker
            engines={engines}
            value={engine}
            onChange={setEngine}
            includeLanguage
            language={language}
            onLanguageChange={setLanguage}
          />
        )}

        <div>
          <label className="block text-sm font-medium mb-1.5">
            Base voice
            <span className="ml-2 text-xs text-[color:var(--muted)] font-normal">
              sets default slider positions
            </span>
          </label>
          <select
            className="select"
            value={baseVoice}
            onChange={(e) => selectPreset(e.target.value)}
            disabled={!presets.length}
          >
            {presets.length === 0 && <option>Loading presets…</option>}
            {presets.map((p) => (
              <option key={p.id} value={p.id}>
                {p.label}
              </option>
            ))}
          </select>
        </div>

        <Slider
          label="Pitch"
          unit="semitones"
          min={-6}
          max={6}
          step={0.5}
          value={sliders.pitch}
          onChange={(v) => update("pitch", v)}
        />
        <Slider
          label="Speed"
          unit="x"
          min={0.5}
          max={2}
          step={0.05}
          value={sliders.speed}
          onChange={(v) => update("speed", v)}
        />
        <Slider
          label="Temperature"
          unit=""
          min={0.1}
          max={1.5}
          step={0.05}
          value={sliders.temperature}
          onChange={(v) => update("temperature", v)}
          hint="Higher = more expressive, more variance"
        />

        <div>
          <label className="block text-sm font-medium mb-1.5">Preview text</label>
          <textarea
            className="input"
            rows={2}
            value={previewText}
            onChange={(e) => setPreviewText(e.target.value)}
          />
        </div>

        <div className="flex items-center gap-3 pt-2 flex-wrap">
          <button
            className="btn"
            onClick={onPreview}
            disabled={!!busy || !baseVoice}
            title="Synthesize without saving — listen before committing"
          >
            {busy === "preview" ? "Generating preview…" : "▶ Preview"}
          </button>
          <button
            className="btn btn-primary"
            onClick={onSave}
            disabled={!!busy || !name.trim() || !baseVoice}
          >
            {busy === "save" ? "Saving…" : "Save voice"}
          </button>
          <button
            className="btn btn-ghost"
            onClick={() => setSliders(DEFAULT_SLIDERS)}
            disabled={!!busy}
          >
            Reset sliders
          </button>
          {error && <span className="text-sm text-red-500">{error}</span>}
        </div>

        {previewUrl && !result && (
          <div className="card mt-3">
            <div className="text-xs text-[color:var(--muted)] mb-2">
              Preview (not saved)
            </div>
            <audio
              controls
              autoPlay
              className="w-full"
              src={previewUrl}
              onPlay={() => setAudioPlaying(true)}
              onPause={() => setAudioPlaying(false)}
              onEnded={() => setAudioPlaying(false)}
            />
            <div className="text-xs text-[color:var(--muted)] mt-2">
              Sound good? Name it above and hit <strong>Save voice</strong>.
            </div>
          </div>
        )}
      </div>

      <div className="flex flex-col items-center">
        <VoiceSphere
          seed={result?.id ?? previewSeed}
          size={220}
          speaking={audioPlaying}
        />
        {result ? (
          <div className="mt-5 w-full space-y-3">
            <div className="text-center">
              <div className="font-medium">{result.name}</div>
              <div className="text-xs text-[color:var(--muted)] mt-0.5">
                Designed · {result.synced ? "synced to Reader" : "local only"}
              </div>
            </div>
            <audio
              controls
              className="w-full"
              src={sampleUrl(result.id)}
              onPlay={() => setAudioPlaying(true)}
              onPause={() => setAudioPlaying(false)}
              onEnded={() => setAudioPlaying(false)}
            />
          </div>
        ) : (
          <div className="mt-5 text-center text-xs text-[color:var(--muted)] max-w-xs">
            Palette updates live as you move the sliders. Hit <em>Create voice</em>{" "}
            to synthesize a preview.
          </div>
        )}
      </div>
    </div>
  );
}

function Slider(props: {
  label: string;
  unit: string;
  min: number;
  max: number;
  step: number;
  value: number;
  onChange: (v: number) => void;
  hint?: string;
}) {
  return (
    <div>
      <div className="flex items-baseline justify-between mb-1.5">
        <label className="block text-sm font-medium">{props.label}</label>
        <span className="text-xs text-[color:var(--muted)] tabular-nums">
          {props.value.toFixed(props.step < 0.1 ? 2 : 1)}
          {props.unit ? ` ${props.unit}` : ""}
        </span>
      </div>
      <input
        type="range"
        min={props.min}
        max={props.max}
        step={props.step}
        value={props.value}
        onChange={(e) => props.onChange(Number(e.target.value))}
        className="w-full accent-[color:var(--accent)]"
      />
      {props.hint && (
        <div className="text-xs text-[color:var(--muted)] mt-1">{props.hint}</div>
      )}
    </div>
  );
}
