// Thin typed wrapper over the FastAPI backend. Next.js rewrites /api/*
// to http://127.0.0.1:8000/api/* so relative paths are fine.

export type VoiceKind = "cloned" | "designed";

export type Profile = {
  id: string;
  name: string;
  kind: VoiceKind;
  engine: string;
  created_at: string;
  design: {
    base_voice?: string;
    pitch?: number;
    speed?: number;
    temperature?: number;
  };
  synced: boolean;
};

export type Preset = {
  id: string;
  label: string;
  file: string;
  ref_text: string;
};

export type Health = {
  ok: boolean;
  reader_configured: boolean;
  reader_base_url: string | null;
  device: string;
  engine: string;
};

async function j<T>(r: Response): Promise<T> {
  if (!r.ok) {
    const body = await r.text().catch(() => "");
    throw new Error(`${r.status} ${r.statusText}${body ? `: ${body.slice(0, 300)}` : ""}`);
  }
  return r.json();
}

export async function getHealth(): Promise<Health> {
  return j(await fetch("/api/health"));
}

export async function listPresets(): Promise<Preset[]> {
  const d = await j<{ presets: Preset[] }>(await fetch("/api/presets"));
  return d.presets;
}

export async function listProfiles(): Promise<Profile[]> {
  const d = await j<{ profiles: Profile[] }>(await fetch("/api/profiles"));
  return d.profiles;
}

export async function deleteProfile(id: string): Promise<void> {
  await j(await fetch(`/api/profiles/${id}`, { method: "DELETE" }));
}

export async function syncProfile(id: string): Promise<Profile> {
  return j(await fetch(`/api/profiles/${id}/sync`, { method: "POST" }));
}

export function sampleUrl(id: string): string {
  return `/api/profiles/${id}/sample`;
}

export async function cloneVoice(args: {
  name: string;
  file: File;
  previewText?: string;
  refText?: string;
  upload?: boolean;
}): Promise<Profile> {
  const fd = new FormData();
  fd.append("name", args.name);
  fd.append("audio_file", args.file);
  if (args.previewText) fd.append("preview_text", args.previewText);
  if (args.refText) fd.append("ref_text", args.refText);
  fd.append("upload", String(args.upload !== false));
  return j(await fetch("/api/clone", { method: "POST", body: fd }));
}

export async function designVoice(args: {
  name: string;
  baseVoice: string;
  pitch: number;
  speed: number;
  temperature: number;
  previewText?: string;
  upload?: boolean;
}): Promise<Profile> {
  const url = `/api/design?upload=${args.upload !== false}`;
  return j(
    await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        name: args.name,
        base_voice: args.baseVoice,
        pitch: args.pitch,
        speed: args.speed,
        temperature: args.temperature,
        preview_text:
          args.previewText ??
          "Hello. This is a preview of my voice, generated by Voice Studio.",
      }),
    })
  );
}
