// Thin typed wrapper over the FastAPI backend. Next.js rewrites /api/*
// to http://127.0.0.1:8000/api/* so relative paths are fine.

export type VoiceKind = "cloned" | "designed";

export type Profile = {
  id: string;
  name: string;
  kind: VoiceKind;
  engine: string;
  created_at: string;
  design: {
    base_voice?: string;
    pitch?: number;
    speed?: number;
    temperature?: number;
  };
  synced: boolean;
};

export type Preset = {
  id: string;
  label: string;
  default_pitch: number;
  default_speed: number;
  default_temperature: number;
};

export type Engine = {
  id: string;
  label: string;
  license: string;
  languages: string[];
  loaded: boolean;
  available: boolean;
  device: string;
};

export type Health = {
  ok: boolean;
  reader_configured: boolean;
  reader_base_url: string | null;
  device: string;
  default_engine: string;
  engines: Engine[];
};

async function j<T>(r: Response): Promise<T> {
  if (!r.ok) {
    const body = await r.text().catch(() => "");
    throw new Error(`${r.status} ${r.statusText}${body ? `: ${body.slice(0, 300)}` : ""}`);
  }
  return r.json();
}

export async function getHealth(): Promise<Health> {
  return j(await fetch("/api/health"));
}

export async function listPresets(): Promise<Preset[]> {
  const d = await j<{ presets: Preset[] }>(await fetch("/api/presets"));
  return d.presets;
}

export async function listEngines(): Promise<{ default: string; engines: Engine[] }> {
  return j(await fetch("/api/engines"));
}

export async function listProfiles(): Promise<Profile[]> {
  const d = await j<{ profiles: Profile[] }>(await fetch("/api/profiles"));
  return d.profiles;
}

export async function deleteProfile(id: string): Promise<void> {
  await j(await fetch(`/api/profiles/${id}`, { method: "DELETE" }));
}

export async function syncProfile(id: string): Promise<Profile> {
  return j(await fetch(`/api/profiles/${id}/sync`, { method: "POST" }));
}

export function sampleUrl(id: string): string {
  return `/api/profiles/${id}/sample`;
}

function cloneFormData(args: {
  name?: string;
  file: File;
  engine: string;
  language?: string;
  previewText?: string;
  refText?: string;
}): FormData {
  const fd = new FormData();
  if (args.name) fd.append("name", args.name);
  fd.append("audio_file", args.file);
  fd.append("engine_id", args.engine);
  fd.append("language", args.language ?? "en");
  if (args.previewText) fd.append("preview_text", args.previewText);
  if (args.refText) fd.append("ref_text", args.refText);
  return fd;
}

export async function cloneVoice(args: {
  name: string;
  file: File;
  engine: string;
  language?: string;
  previewText?: string;
  refText?: string;
  upload?: boolean;
}): Promise<Profile> {
  const fd = cloneFormData(args);
  fd.append("upload", String(args.upload !== false));
  fd.append("save", "true");
  return j(await fetch("/api/clone", { method: "POST", body: fd }));
}

/** Preview a cloned voice without persisting. Returns an object URL for
 * an <audio> element — revoke it (URL.revokeObjectURL) when done. */
export async function previewClone(args: {
  file: File;
  engine: string;
  language?: string;
  previewText?: string;
  refText?: string;
}): Promise<string> {
  const fd = cloneFormData(args);
  fd.append("save", "false");
  const r = await fetch("/api/clone", { method: "POST", body: fd });
  if (!r.ok) {
    const body = await r.text().catch(() => "");
    throw new Error(
      `${r.status} ${r.statusText}${body ? `: ${body.slice(0, 300)}` : ""}`
    );
  }
  const blob = await r.blob();
  return URL.createObjectURL(blob);
}

function designBody(args: {
  name?: string;
  baseVoice: string;
  engine: string;
  language?: string;
  pitch: number;
  speed: number;
  temperature: number;
  previewText?: string;
}): string {
  return JSON.stringify({
    // The /preview endpoint ignores `name` but we still send something so
    // server-side pydantic doesn't reject it (min_length=1).
    name: args.name || "Preview",
    base_voice: args.baseVoice,
    engine: args.engine,
    language: args.language ?? "en",
    pitch: args.pitch,
    speed: args.speed,
    temperature: args.temperature,
    preview_text:
      args.previewText ??
      "Hello. This is a preview of my voice, generated by Voice Studio.",
  });
}

export async function designVoice(args: {
  name: string;
  baseVoice: string;
  engine: string;
  language?: string;
  pitch: number;
  speed: number;
  temperature: number;
  previewText?: string;
  upload?: boolean;
}): Promise<Profile> {
  const url = `/api/design?upload=${args.upload !== false}`;
  return j(
    await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: designBody(args),
    })
  );
}

/** Preview a designed voice without persisting. Returns a blob object URL. */
export async function previewDesign(args: {
  baseVoice: string;
  engine: string;
  language?: string;
  pitch: number;
  speed: number;
  temperature: number;
  previewText?: string;
}): Promise<string> {
  const r = await fetch("/api/design/preview", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: designBody(args),
  });
  if (!r.ok) {
    const body = await r.text().catch(() => "");
    throw new Error(
      `${r.status} ${r.statusText}${body ? `: ${body.slice(0, 300)}` : ""}`
    );
  }
  const blob = await r.blob();
  return URL.createObjectURL(blob);
}
